### ISSUE TITLE
Clear only clears the chat, but not the actual history

### ISSUE THREAD

**Issue by JiaCYu** [Wannabeasmartguy/GPT-Gradio-Agent#2]
When I press clear, the agent still has memory of what was cleared:
# First prompt
![image](https://github.com/Wannabeasmartguy/GPT-Gradio-Agent/assets/145611451/b652b464-5156-426a-a0ba-e1affbf296ba)
# Clear and Type second prompt
![image](https://github.com/Wannabeasmartguy/GPT-Gradio-Agent/assets/145611451/e9a7ba93-00f9-422f-b3a3-cf5d50413a41)

**Comment by Wannabeasmartguy** [comment]
Thanks for your feedback! That's a careless omission which I forget to reset the memory. It will be fixed soon.

**Comment by Wannabeasmartguy** [comment]
It has been fixed up in v0.5.0.1, now you can properly clear the history.
